lsi: false
safe: true
incremental: false
title: Treu - SoC - Utah
description: REU website 
show_downloads: false 
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
